! Generated by atfmsched.pl Version 1.1
! From reddragon.reddragon.com (206.112.139.2)
! As Observer Code "nel"
! On Fri Feb  6 15:26:04 GMT 1998
! With Mozilla/3.0 (Win95; U; 16bit)

TITLE = 'm51'
OBSERVER = 'Donald Regan'

! Scan set 1
    BLOCK = '00:30:00' 
    # CATALOG = 'messier'
    SOURCE = 'ngc777'
    FILTER = 'V,R,B' DURATION = '60,30,90'
    ccdcalib = 'cat'
    # imagedir = '/home/ecdowney'
    /
BLOCKREPEAT 1

! For RCS Only -- Do Not Edit
! @(#) $RCSfile: sample.sch,v $ $Date: 2001/04/19 21:12:01 $ $Revision: 1.1.1.1 $ $Name:  $
