#! /usr/bin/perl
# convert Tmp.edb created by revngc.pl to Messier.edb
# Submitted 22 Jun 2000 by Fridger Schrempp, fridger.schrempp@desy.de

open (TMP, "<Tmp.edb")|| die "Can not read Tmp.edb\n";
open (M, ">Messier.edb")|| die "Can not create Messier.edb\n";

# boilerplate
($ver = '$Revision: 1.1.1.1 $') =~ s/\$//g;
($me = $0) =~ s/.*\///;
($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = gmtime;
$year += 1900;
$mon += 1;
print M "# Messier catalog, from NGC/IC Project\n";
print M "# Data From http://www.ngcic.org/steinicke/2000/revngc.txt\n";
print M "# Generated by $me $ver\n";
print M "# Processed $year-$mon-$mday $hour:$min:$sec UTC\n";

# Rewrite the Messier catalog as to be used in xephem
while (<TMP>){
    $_ =~ s/\sNGC\s\d{3,4}//g;
    $_ =~ s/^\#\s//g;
    $_ =~ s/(M)\s/\1/; 
    print M $_;
    # Add missing/non-existing Messier Objects in numeric order
    if ($_ =~/^M24\b/){print M "M25,f|O,18:31:36,-19:15,4.6,2000,1920\n";}
    if ($_ =~/^M39\b/){print M "M40,f|D,12:21:54,58:06,9,2000\n";}
    if ($_ =~/^M44\b/){print M "M45,f|U,03:47:0,24:07,1.2,2000,6000\n";}
}

# For RCS Only -- Do Not Edit
# @(#) $RCSfile: messier.pl,v $ $Date: 2001/04/19 21:12:06 $ $Revision: 1.1.1.1 $ $Name:  $
