#!/usr/bin/perl
# convert snrs.dat on stdin to snrs.edb on stdout.
#
# This script is Copyright (c) 1999 Elwood Downey
#  3 May 1999: first draft

# mimic RCS version
$ver = '$Revision: 1.1.1.1 $';
$ver =~ s/\$//g;

# intro
($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = gmtime;
$year += 1900;
$mon += 1;
print "# Green D.A., 1998, `A Catalogue of Galactic Supernova Remnants\n";
print "#   (1998 September version)', Mullard Radio Astronomy Observatory,\n";
print "#   Cambridge, United Kingdom\n";
print "# See http://www.mrao.cam.ac.uk/surveys/snrs\n";
print "#   and ftp://adc.gsfc.nasa.gov/pub/adc/archives/catalogs/7/7211\n";
print "# Processed $year-$mon-$mday $hour:$min:$sec UTC\n";
print "# Generated by snrs2edb.pl $ver by Elwood Downey\n";
print "#   'Name' is first of \"Other\", else G<l><b>\n";
print "#   'Magnitude' is 8.586-2.5*&log10(Janskys), result is 0..10.\n";
print "#   'Size' is diameter, or major axis\n";

# process each snrs.dat entry
while (<STDIN>) {
    chomp();

    # 1950
    $rh = &s(15,16);
    $rm = &s(18,19);
    $rs = &s(21,22);
    $ds = &s(25,25);
    $dd = &s(26,27);
    $dm = &s(29,30);

    # size.. diameter or major axis if elliptical
    $ss = &s(33,39);
    $ss =~ s/x.*//;
    $sz = $ss * 60;

    # mag.. use log(Jansky) in "magnitudes" scaled so brightest in file is 0.
    # dimmest is 0.4 which yields 9.58. a few are missing, set to 10.
    $jy = &s(46,51);
    $mag = sprintf ("%.2f", $jy == 0 ? 10 : 8.586-2.5*&log10($jy));

    # name.. up to first comma in "other" else G<l><b> sans blanks
    $name = &s(61,86);
    $name =~ s/,.*//;
    $name =~ s/[)(]//g;
    if ($name eq "") {
	$l = &s(2,6);
	$l =~ s/ //g;
	$b = &s(8,12);
	$b =~ s/ //g;
	$name = "G$l$b";
    }

    # print
    print "$name,f|R,$rh:$rm:$rs,$ds$dd:$dm,$mag,1950,$sz\n";
}

# like substr($_,first,last), but one-based.
sub s {
    substr ($_, $_[0]-1, $_[1]-$_[0]+1);
}

# return log base 10
sub log10 {
    .43429*log($_[0]);
}

# For RCS Only -- Do Not Edit
# @(#) $RCSfile: snrs2edb.pl,v $ $Date: 2001/04/19 21:12:06 $ $Revision: 1.1.1.1 $ $Name:  $
