#!/bin/csh -f
# kill all telescope-related daemons and tools.

set common = (rund xobs shm telescoped csimcd csimc telrun)

foreach p ($common)
    echo -n "$p "
    killp -q $p
end

echo ""
echo -n "Cleaning comm"
rm -f $TELHOME/comm/*.pid >& /dev/null
echo -n "."
rm -f $TELHOME/comm/*.in >& /dev/null
echo -n "."
rm -f $TELHOME/comm/*.out >& /dev/null
echo -n "."
echo "OK"

echo ""
