#!/bin/csh -f
# start all telescope-related daemons and tools.

rund telescoped
rund camerad
rund wxd.php -f /usr/local/telescope/archive/logs/wxd.dat -d 1 -h rebei -p 6666 -e 0
rund wxd -st /usr/local/telescope/archive/logs/wxd.dat -l -
rund gpsd -fsac

