OVFERR    =    1          ; /* floating point overflow error */
UNFERR    =    1          ; /* floating point underflow error */
DIV0ERR   =    5          ; /* division by 0 error */
TOLGSMER  =    6          ; /* number too large or small to convert to int. */
NSQRTERR  =    7          ; /* tried to take the square root of negative # */
TAN90ERR  =    8          ; /* TANgent of 90 degrees attempted */
LNNEGERR  =    9          ; /* LOG or LN of negative number or 0 */
ACOSERR   =    10         ; /* Arc cosine not implemented */
ASINERR   =    11         ; /* Arc sine not implemented */
FLTFMTER  =    12         ; /* floating point format error in ASCFLT */
