#!/bin/bash

TELHOME=/usr/local/telescope
export TELHOME
if [ ! -d "${TELHOME}/archive/config" ]; then
#	read -p "Telescope config: " -e TELCONFIG
	TELCONFIG=sqft
	ln -s ./config_${TELCONFIG} ${TELHOME}/archive/config
fi


############################################################################################################
############################################ xephem postinstall ############################################
rm -f ${TELHOME}/xephem/catalogs
rm -f ${TELHOME}/xephem/fifos
rm -f ${TELHOME}/comm/xephem_loc_fifo
rm -f ${TELHOME}/comm/xephem_db_fifo
rm -f ${TELHOME}/comm/xephem_in_fifo
rm -f ${TELHOME}/comm/xephem_out_fifo

ln -s ${TELHOME}/archive/catalogs ${TELHOME}/xephem/catalogs
ln -s ${TELHOME}/comm ${TELHOME}/xephem/fifos
mkfifo -m 0666 ${TELHOME}/comm/xephem_loc_fifo
mkfifo -m 0666 ${TELHOME}/comm/xephem_db_fifo
mkfifo -m 0666 ${TELHOME}/comm/xephem_in_fifo
mkfifo -m 0666 ${TELHOME}/comm/xephem_out_fifo
############################################################################################################



#read -p "Talon username: " -e USER
chown -hR saft:saft /usr/local/telescope

chown root:root ${TELHOME}/bin/gpsd
chmod 6755 ${TELHOME}/bin/gpsd

