#!/bin/csh -f

# Test program to take a picture using camerad

cat << _EOF_ >> $TELHOME/comm/Camera.in
Expose 0+0x1024x1024 1x1 10 1 0 /tmp/image.fts
Nowhere
Hope it works :-)
Testing camerad
ECStars
_EOF_

#fio -s -m Camera

#echo /tmp/image.fts >> /usr/local/telescope/comm/CameraFilename
