#!/bin/bash

# These parameters may need to be changed
FXLOAD_PATH="/sbin"
HEX_PATH="/usr/share/usb"
USB_USERMAP="/etc/hotplug/usb.usermap"
HOTPLUG_USB_PATH="/etc/hotplug/usb"
LIBUSB_SO="/usr/lib/libusb.so"

##########################################################################

# Call this immediately after a command that returns 1 on error
function onError()
{
	result=$?
	text=$1

	if [ $result -ne 0 ]; then
		echo
		echo "$text"
		echo
		exit
	fi
}

if [ $UID -ne 0 ]; then
  echo "Please run as root"
  echo "e.g.  su root ./install_sbig"
  exit
fi

if [ ! -x $FXLOAD_PATH/fxload ]; then
  echo "fxload not found in $FXLOAD_PATH; please install it or change this"
  echo "script to look in the right place"
  exit
fi

echo "Copying .hex and .bin files..."

mkdir -p /usr/share/usb
onError "Error creating $HEX_PATH"

cp *.hex *.bin /usr/share/usb
onError "Error creating $HEX_PATH"

if [ -e $USB_USERMAP ]; then
	grep sbig $USB_USERMAP > /dev/null
	if [ $? -eq 1 ]; then
		echo "Adding SBIG definitions to $USB_USERMAP"
		cat sbig.usermap >> $USB_USERMAP
		onError "Error writing to $USB_USERMAP"
	else
		echo "SBIG definitions already exist in $USB_USERMAP"
	fi
else
		echo "Adding SBIG definitions to $USB_USERMAP"
		cat sbig.usermap >> $USB_USERMAP
		onError "Error writing to $USB_USERMAP"
fi

echo "Copying sbig script to $HOTPLUG_USB_PATH"
chmod +x sbig
mkdir -p $HOTPLUG_USB_PATH
onError "Error creating $HOTPLUG_USB_PATH"

cp sbig $HOTPLUG_USB_PATH
onError "Error copying sbig script to $HOTPLUG_USB_PATH"

if [ ! -e /usr/local/lib/libusb.so ]; then
	if [ -e $LIBUSB_SO ]; then
		echo "Soft-linking $LIBUSB_SO to /usr/local/lib (needed by libsbigudrv)"
		ln -s $LIBUSB_SO /usr/local/lib/libusb.so
	else
		echo "Error: libusb.so not found at $LIBUSB_SO. Please install libusb or change"
		echo "LIBUSB_SO variable in this script to reflect actual location"
		echo
		exit
	fi
else
	echo "/usr/local/lib/libusb already exists; not linking"
fi


echo
cat <<EOF
It looks like everything succeeded; now plug in your SBIG camera
or unplug it and plug it back in. It may be equipped with an LED
which should blink for a few seconds after plugging it in.
EOF


