#!/bin/sh

# Upload firmware into the SBIG USB CCD cameras
#FIRMWARE=/usr/share/usb/sbigucam.hex

FLAGS=
#FIRMWARE=
LOADER=/sbin/fxload

# pre-renumeration device IDs
case $PRODUCT in

# SBIG ST-7/8/9/10/2K cameras
d97/1/*) FIRMWARE=/usr/share/usb/sbigucam.hex ;;

# SBIG ST-L cameras
d97/2/*) FIRMWARE=/usr/share/usb/sbiglcam.hex ;;

# SBIG ST-402/3200/1603 cameras
d97/3/*) FIRMWARE=/usr/share/usb/sbigfcam.hex ; FLAGS="-t fx2";;

# Change device permission for SBIG cams & libusb
d97/101/*) chmod a+w "${DEVICE}"; exit 0

esac

# missing firmware?
if [ ! -r $FIRMWARE ]; then
    if [ -x /usr/bin/logger ]; then
	/usr/bin/logger -t $0 "missing $FIRMWARE for $PRODUCT ??"
    fi
    exit 1
fi

# missing loader?
if [ ! -x $LOADER ]; then
    if [ -x /usr/bin/logger ]; then
	/usr/bin/logger -t $0 "missing $LOADER ??"
    fi
    exit 1
fi

if [ -x /usr/bin/logger ]; then
    /usr/bin/logger -t $0 "load $FIRMWARE for $PRODUCT to $DEVICE"
fi

$LOADER $FLAGS -I $FIRMWARE

