/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JLibFLI */

#ifndef _Included_JLibFLI
#define _Included_JLibFLI
#ifdef __cplusplus
extern "C" {
#endif
#undef JLibFLI_FLI_INVALID_DEVICE
#define JLibFLI_FLI_INVALID_DEVICE -1L
#undef JLibFLI_FLIDOMAIN_NONE
#define JLibFLI_FLIDOMAIN_NONE 0L
#undef JLibFLI_FLIDOMAIN_PARALLEL_PORT
#define JLibFLI_FLIDOMAIN_PARALLEL_PORT 1L
#undef JLibFLI_FLIDOMAIN_USB
#define JLibFLI_FLIDOMAIN_USB 2L
#undef JLibFLI_FLIDOMAIN_SERIAL
#define JLibFLI_FLIDOMAIN_SERIAL 3L
#undef JLibFLI_FLIDOMAIN_INET
#define JLibFLI_FLIDOMAIN_INET 4L
#undef JLibFLI_FLIDOMAIN_SERIAL_19200
#define JLibFLI_FLIDOMAIN_SERIAL_19200 5L
#undef JLibFLI_FLIDOMAIN_SERIAL_1200
#define JLibFLI_FLIDOMAIN_SERIAL_1200 6L
#undef JLibFLI_FLIDEVICE_NONE
#define JLibFLI_FLIDEVICE_NONE 0L
#undef JLibFLI_FLIDEVICE_CAMERA
#define JLibFLI_FLIDEVICE_CAMERA 256L
#undef JLibFLI_FLIDEVICE_FILTERWHEEL
#define JLibFLI_FLIDEVICE_FILTERWHEEL 512L
#undef JLibFLI_FLIDEVICE_FOCUSER
#define JLibFLI_FLIDEVICE_FOCUSER 768L
#undef JLibFLI_FLIDEVICE_ENUMERATE_BY_CONNECTION
#define JLibFLI_FLIDEVICE_ENUMERATE_BY_CONNECTION 32768L
#undef JLibFLI_FLI_FRAME_TYPE_NORMAL
#define JLibFLI_FLI_FRAME_TYPE_NORMAL 0L
#undef JLibFLI_FLI_FRAME_TYPE_DARK
#define JLibFLI_FLI_FRAME_TYPE_DARK 1L
#undef JLibFLI_FLI_FRAME_TYPE_FLOOD
#define JLibFLI_FLI_FRAME_TYPE_FLOOD 2L
#undef JLibFLI_FLI_FRAME_TYPE_RBI_FLUSH
#define JLibFLI_FLI_FRAME_TYPE_RBI_FLUSH 3L
#undef JLibFLI_FLI_SHUTTER_CLOSE
#define JLibFLI_FLI_SHUTTER_CLOSE 0L
#undef JLibFLI_FLI_SHUTTER_OPEN
#define JLibFLI_FLI_SHUTTER_OPEN 1L
#undef JLibFLI_FLI_SHUTTER_EXTERNAL_TRIGGER
#define JLibFLI_FLI_SHUTTER_EXTERNAL_TRIGGER 2L
#undef JLibFLI_FLI_SHUTTER_EXTERNAL_TRIGGER_LOW
#define JLibFLI_FLI_SHUTTER_EXTERNAL_TRIGGER_LOW 2L
#undef JLibFLI_FLI_SHUTTER_EXTERNAL_TRIGGER_HIGH
#define JLibFLI_FLI_SHUTTER_EXTERNAL_TRIGGER_HIGH 4L
#undef JLibFLI_FLI_BGFLUSH_STOP
#define JLibFLI_FLI_BGFLUSH_STOP 0L
#undef JLibFLI_FLI_BGFLUSH_START
#define JLibFLI_FLI_BGFLUSH_START 1L
#undef JLibFLI_FLI_TEMPERATURE_INTERNAL
#define JLibFLI_FLI_TEMPERATURE_INTERNAL 0L
#undef JLibFLI_FLI_TEMPERATURE_EXTERNAL
#define JLibFLI_FLI_TEMPERATURE_EXTERNAL 1L
#undef JLibFLI_FLI_TEMPERATURE_CCD
#define JLibFLI_FLI_TEMPERATURE_CCD 0L
#undef JLibFLI_FLI_TEMPERATURE_BASE
#define JLibFLI_FLI_TEMPERATURE_BASE 1L
#undef JLibFLI_FLI_CAMERA_STATUS_UNKNOWN
#define JLibFLI_FLI_CAMERA_STATUS_UNKNOWN -1L
#undef JLibFLI_FLI_CAMERA_STATUS_MASK
#define JLibFLI_FLI_CAMERA_STATUS_MASK 255L
#undef JLibFLI_FLI_CAMERA_STATUS_IDLE
#define JLibFLI_FLI_CAMERA_STATUS_IDLE 0L
#undef JLibFLI_FLI_CAMERA_STATUS_WAITING_FOR_TRIGGER
#define JLibFLI_FLI_CAMERA_STATUS_WAITING_FOR_TRIGGER 1L
#undef JLibFLI_FLI_CAMERA_STATUS_EXPOSING
#define JLibFLI_FLI_CAMERA_STATUS_EXPOSING 2L
#undef JLibFLI_FLI_CAMERA_STATUS_READING_CCD
#define JLibFLI_FLI_CAMERA_STATUS_READING_CCD 3L
#undef JLibFLI_FLI_CAMERA_DATA_READY
#define JLibFLI_FLI_CAMERA_DATA_READY -2147483648L
#undef JLibFLI_FLI_FOCUSER_STATUS_UNKNOWN
#define JLibFLI_FLI_FOCUSER_STATUS_UNKNOWN -1L
#undef JLibFLI_FLI_FOCUSER_STATUS_HOMING
#define JLibFLI_FLI_FOCUSER_STATUS_HOMING 4L
#undef JLibFLI_FLI_FOCUSER_STATUS_MOVING_IN
#define JLibFLI_FLI_FOCUSER_STATUS_MOVING_IN 1L
#undef JLibFLI_FLI_FOCUSER_STATUS_MOVING_OUT
#define JLibFLI_FLI_FOCUSER_STATUS_MOVING_OUT 2L
#undef JLibFLI_FLI_FOCUSER_STATUS_MOVING_MASK
#define JLibFLI_FLI_FOCUSER_STATUS_MOVING_MASK 7L
#undef JLibFLI_FLI_FOCUSER_STATUS_HOME
#define JLibFLI_FLI_FOCUSER_STATUS_HOME 128L
#undef JLibFLI_FLI_FOCUSER_STATUS_LEGACY
#define JLibFLI_FLI_FOCUSER_STATUS_LEGACY 268435456L
#undef JLibFLI_FLIDEBUG_NONE
#define JLibFLI_FLIDEBUG_NONE 0L
#undef JLibFLI_FLIDEBUG_INFO
#define JLibFLI_FLIDEBUG_INFO 1L
#undef JLibFLI_FLIDEBUG_WARN
#define JLibFLI_FLIDEBUG_WARN 2L
#undef JLibFLI_FLIDEBUG_FAIL
#define JLibFLI_FLIDEBUG_FAIL 4L
#undef JLibFLI_FLIDEBUG_ALL
#define JLibFLI_FLIDEBUG_ALL 7L
#undef JLibFLI_FLI_IO_P0
#define JLibFLI_FLI_IO_P0 1L
#undef JLibFLI_FLI_IO_P1
#define JLibFLI_FLI_IO_P1 2L
#undef JLibFLI_FLI_IO_P2
#define JLibFLI_FLI_IO_P2 4L
#undef JLibFLI_FLI_IO_P3
#define JLibFLI_FLI_IO_P3 8L
/*
 * Class:     JLibFLI
 * Method:    FLIGetLibVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JLibFLI_FLIGetLibVersion
  (JNIEnv *, jobject);

/*
 * Class:     JLibFLI
 * Method:    FLIOpen
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_JLibFLI_FLIOpen
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     JLibFLI
 * Method:    FLIClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JLibFLI_FLIClose
  (JNIEnv *, jobject, jint);

/*
 * Class:     JLibFLI
 * Method:    FLIGetModel
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JLibFLI_FLIGetModel
  (JNIEnv *, jobject, jint);

/*
 * Class:     JLibFLI
 * Method:    FLIGetHWRevision
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JLibFLI_FLIGetHWRevision
  (JNIEnv *, jobject, jint);

/*
 * Class:     JLibFLI
 * Method:    FLIGetFWRevision
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JLibFLI_FLIGetFWRevision
  (JNIEnv *, jobject, jint);

/*
 * Class:     JLibFLI
 * Method:    FLIGetArrayArea
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_JLibFLI_FLIGetArrayArea
  (JNIEnv *, jobject, jint);

/*
 * Class:     JLibFLI
 * Method:    FLIGetVisibleArea
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_JLibFLI_FLIGetVisibleArea
  (JNIEnv *, jobject, jint);

/*
 * Class:     JLibFLI
 * Method:    FLIGetPixelSize
 * Signature: (I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_JLibFLI_FLIGetPixelSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     JLibFLI
 * Method:    FLISetExposureTime
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JLibFLI_FLISetExposureTime
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JLibFLI
 * Method:    FLISetImageArea
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_JLibFLI_FLISetImageArea
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     JLibFLI
 * Method:    FLISetHBin
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JLibFLI_FLISetHBin
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JLibFLI
 * Method:    FLISetVBin
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JLibFLI_FLISetVBin
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JLibFLI
 * Method:    FLICancelExposure
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JLibFLI_FLICancelExposure
  (JNIEnv *, jobject, jint);

/*
 * Class:     JLibFLI
 * Method:    FLIGetExposureStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JLibFLI_FLIGetExposureStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     JLibFLI
 * Method:    FLISetTemperature
 * Signature: (ID)I
 */
JNIEXPORT jint JNICALL Java_JLibFLI_FLISetTemperature
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     JLibFLI
 * Method:    FLIGetTemperature
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_JLibFLI_FLIGetTemperature
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JLibFLI
 * Method:    FLIExposeFrame
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JLibFLI_FLIExposeFrame
  (JNIEnv *, jobject, jint);

/*
 * Class:     JLibFLI
 * Method:    FLIGrabRow
 * Signature: (II[S)I
 */
JNIEXPORT jint JNICALL Java_JLibFLI_FLIGrabRow
  (JNIEnv *, jobject, jint, jint, jshortArray);

/*
 * Class:     JLibFLI
 * Method:    FLISetFrameType
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JLibFLI_FLISetFrameType
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
